baseURL: "https://lesliexxy.github.io/xinyuexu.github.io/"
title: Xinyue (Leslie) Xu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
          # weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Xinyue (Leslie) Xu's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Xinyue (Leslie) Xu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "Nov 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Research assistant
          subtitle: "I am a senior Ph. D. candidate in the Department of Architectural Engineering at Penn State. 
          I am a researcher specializing in Physics-Informed Machine Learning (PIML) and Bayesian inference for uncertainty-aware modeling of complex engineering systems. 
          My work bridges computational science and building engineering, developing scalable probabilistic frameworks that integrate physical laws into AI models to improve predictive robustness, interpretability, and generalization. 
          I have published multiple peer-reviewed papers in high-impact journals on model selection, uncertainty quantification, and physics-guided Bayesian neural networks, with applications ranging from vibration dynamics to large-scale residential building energy systems. 
          Proficient in Python, MATLAB, COMSOL, and ANSYS, I combine physics-based modeling with modern ML pipelines to advance data-driven engineering design and simulation under uncertainty"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publication
              url: papers/
            - name: Research Project
              url: projects/
            - name: Tags
              url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Life
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:xkx5055@psu.edu
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zJpzOSEAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Lesliexxy?tab=repositories
        - name: LinkedIn
          url: hhttps://www.linkedin.com/in/xinyue-xu-8a4a74184/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Xinyue (Leslie) Xu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2